spring:
  application:
    name: meudiariodeobras
  profiles:
    active: ${ENV_SPRING_PROFILE:default}
  config:
    import:  optional:classpath:.env[.properties]
  datasource:
      url: ${ENV_DB_URL}
      username: ${ENV_DB_USERNAME}
      password: ${ENV_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: ${ENV_MAIL_HOST}
    port: ${ENV_MAIL_PORT}
    username: ${ENV_MAIL_USERNAME}
    password: ${ENV_MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          from: ${ENV_MAIL_FROM_ADDRESS}
    default-encoding: UTF-8
    test-connection: false
mail:
  from:
    name: ${ENV_MAIL_FROM_NAME}
jwt:
  secret: ${ENV_JWT_SECRET}
  expiration: ${ENV_JWT_EXPIRATION}

refresh-token:
  expiration: ${ENV_REFRESH_TOKEN_EXPIRATION}

aws:
  secretAccessKey: ${ENV_AWS_SECRET_KEY}
  accessKeyId: ${ENV_AWS_ACCESS_KEY}
  s3:
    bucketName: ${ENV_AWS_S3_BUCKET_NAME}
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
stripe:
  secret-key: ${ENV_STRIPE_API_KEY}
  secret-webhook: ${ENV_STRIPE_WEBHOOK_SECRET}
  success-url: ${ENV_STRIPE_SUCCESS_URL}
  cancel-url: ${ENV_STRIPE_CANCEL_URL}