spring:
  application:
    name: meudiariodeobras
  config:
    import:  optional:classpath:.env[.properties]
  datasource:
      url: ${ENV_DB_URL}
      username: ${ENV_DB_USERNAME}
      password: ${ENV_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
jwt:
    secret: ${ENV_JWT_SECRET}
    expiration: ${ENV_JWT_EXPIRATION}

aws:
  secretAccessKey: ${ENV_AWS_SECRET_KEY}
  accessKeyId: ${ENV_AWS_ACCESS_KEY}
  s3:
    bucketName: ${ENV_AWS_S3_BUCKET_NAME}
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
stripe:
  secret-key: ${ENV_STRIPE_API_KEY}
  secret-webhook: ${ENV_STRIPE_WEBHOOK_SECRET}
  success-url: ${ENV_STRIPE_SUCCESS_URL}
  cancel-url: ${ENV_STRIPE_CANCEL_URL}